# Generated by Django 5.0.3 on 2024-08-05 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_trznica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kosarica',
            options={'verbose_name': 'kosarica', 'verbose_name_plural': 'kosarica'},
        ),
    ]
