# Generated by Django 5.0.3 on 2024-08-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_trznica', '0002_alter_kosarica_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta_poreza', models.CharField(max_length=20, unique=True)),
                ('postotak_poreza', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Postotak poreza (%)')),
                ('aktivno', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'porez',
                'verbose_name_plural': 'porezi',
            },
        ),
    ]
