# Generated by Django 5.0.3 on 2024-04-16 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('korisnicki_racuni', '0003_alter_korisnickiprofil_options_alter_user_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_opga', models.CharField(max_length=100)),
                ('potvrda_opga', models.ImageField(upload_to='opg/potvrda')),
                ('opg_verificiran', models.BooleanField(default=False)),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('izmijenjeno', models.DateTimeField(auto_now=True)),
                ('korisnicki_profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='korisnicki_profil', to='korisnicki_racuni.korisnickiprofil')),
                ('korisnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='korisnik', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Opg-ovi',
            },
        ),
    ]
