# Generated by Django 5.0.3 on 2024-05-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opg',
            name='opg_slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
