# Generated by Django 5.0.3 on 2024-05-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opg', '0002_opg_opg_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opg',
            name='opg_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
