# Generated by Django 5.0.3 on 2024-04-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korisnicki_racuni', '0002_korisnickiprofil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='korisnickiprofil',
            options={'verbose_name': 'korisnicki profil', 'verbose_name_plural': 'korisnicki profili'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'korisnik', 'verbose_name_plural': 'korisnici'},
        ),
    ]
