# Generated by Django 5.0.3 on 2024-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnicki_racuni', '0003_alter_korisnickiprofil_options_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnickiprofil',
            name='adresa_1',
        ),
        migrations.RemoveField(
            model_name='korisnickiprofil',
            name='adresa_2',
        ),
        migrations.AddField(
            model_name='korisnickiprofil',
            name='adresa',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
