# Generated by Django 5.0.3 on 2024-08-06 18:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korisnicki_racuni', '0004_remove_korisnickiprofil_adresa_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnickiprofil',
            name='lokacija',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
