# Generated by Django 5.0.3 on 2024-05-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opg_ponuda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorijeproizvoda',
            options={'verbose_name': 'Kategorije proizvoda', 'verbose_name_plural': 'Kategorije proizvoda'},
        ),
        migrations.AlterModelOptions(
            name='proizvodi',
            options={'verbose_name': 'Proizvodi', 'verbose_name_plural': 'Proizvodi'},
        ),
        migrations.AlterField(
            model_name='kategorijeproizvoda',
            name='naziv_kategorije',
            field=models.CharField(unique=True, verbose_name=50),
        ),
        migrations.AlterField(
            model_name='proizvodi',
            name='naziv_proizvoda',
            field=models.CharField(max_length=50),
        ),
    ]
