# Generated by Django 5.0.3 on 2024-08-03 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opg_ponuda', '0003_alter_kategorijeproizvoda_naziv_kategorije'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proizvodi',
            name='kategorija_proizvoda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proizvodi', to='opg_ponuda.kategorijeproizvoda'),
        ),
    ]
