# Generated by Django 5.0.3 on 2024-08-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opg_ponuda', '0004_alter_proizvodi_kategorija_proizvoda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorijeproizvoda',
            name='naziv_kategorije',
            field=models.CharField(max_length=50),
        ),
    ]
