# Generated by Django 5.0.3 on 2024-08-11 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opg_ponuda', '0005_alter_kategorijeproizvoda_naziv_kategorije'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Placanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transakcije', models.CharField(max_length=100)),
                ('nacin_placanja', models.CharField(choices=[('PayPal', 'PayPal')], max_length=100)),
                ('iznos', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=100)),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_narudzbe', models.CharField(max_length=20)),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('broj_telefona', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('adresa', models.CharField(max_length=200)),
                ('drzava', models.CharField(blank=True, max_length=50)),
                ('zupanija', models.CharField(blank=True, max_length=50)),
                ('grad', models.CharField(max_length=50)),
                ('postanski_broj', models.CharField(max_length=10)),
                ('ukupno', models.FloatField()),
                ('porezni_podaci', models.JSONField(blank=True, help_text="Format podataka: {'vrsta_poreza':{'postotak_poreza':'iznos_poreza'}}")),
                ('ukupno_poreza', models.FloatField()),
                ('nacin_placanja', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('U tijeku', 'U tijeku'), ('Prihvaćena', 'Prihvaćena'), ('Završena', 'Završena'), ('Otkazana', 'Otkazana')], default='U tijeku', max_length=15)),
                ('naruceno', models.BooleanField(default=False)),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('izmijenjeno', models.DateTimeField(auto_now=True)),
                ('korisnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('placanje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='narudzbe.placanje')),
            ],
        ),
        migrations.CreateModel(
            name='NaruceniProizvodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField()),
                ('cijena', models.FloatField()),
                ('iznos', models.FloatField()),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('izmijenjeno', models.DateTimeField(auto_now=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opg_ponuda.proizvodi')),
                ('narudzba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='narudzbe.narudzba')),
                ('placanje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='narudzbe.placanje')),
            ],
        ),
    ]
