# Generated by Django 5.0.3 on 2024-09-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narudzbe', '0001_initial'),
        ('opg', '0003_alter_opg_opg_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naruceniproizvodi',
            options={'verbose_name': 'Naruceni proizvod', 'verbose_name_plural': 'Naruceni proizvodi'},
        ),
        migrations.AlterModelOptions(
            name='narudzba',
            options={'verbose_name': 'Narudzba', 'verbose_name_plural': 'Narudzbe'},
        ),
        migrations.AlterModelOptions(
            name='placanje',
            options={'verbose_name': 'Placanje', 'verbose_name_plural': 'Placanja'},
        ),
        migrations.AddField(
            model_name='narudzba',
            name='opgovi',
            field=models.ManyToManyField(blank=True, to='opg.opg'),
        ),
        migrations.AddField(
            model_name='narudzba',
            name='ukupni_podaci',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
