# Generated by Django 5.0.3 on 2024-09-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narudzbe', '0002_alter_naruceniproizvodi_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narudzba',
            name='porezni_podaci',
            field=models.JSONField(blank=True, help_text="Format podataka: {'vrsta_poreza':{'postotak_poreza':'iznos_poreza'}}", null=True),
        ),
    ]
